language: go

go:
  - 1.15.x
  - 1.16.x
  - 1.17.x
  - 1.18.x

before_script:
  - go get golang.org/x/lint
  - go get ./...

script:
  - go vet ./...
  #- golint ./...
  - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

