#!/usr/bin/env sh

#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# Need to create an install script to put the rules into the config directory
# Need to create an install script to put this somewhere executable
# Need to have a solid way to stop the commit if the output detects secrets
# Need to document this, currently it will only scan all files that are local, it does not scan and git stuff as this runs pre-commit
